### ISSUE TITLE
Weekly, monthly, and yearly data

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [mikedbjones/longtrends#3]
Can you add an argument to allow plotting weekly, monthly, and yearly data from Gtrends? This data can be retrieved by specifying a delta longer than 269.

**Comment by mikedbjones** [comment]
The purpose of this package is to provide long term, daily trends. For weekly or otherwise, you can use Google Trends as you say. But with the latter, you cannot download daily trends over a long time period.

**Comment by asdsadsaasd12312132** [comment]
Weekly data has the same limitation as daily. There's a limit of 1889 days/270 weeks before it defaults to monthly data. I assume the monthly data would also default to yearly data once it hits 270 months, but that's 22.5 years later. The main problem is with weekly data, which can cause problems since the limit is only 5.2 years.
