### ISSUE TITLE
How to disable indexing

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [mikedbjones/longtrends#4]
The data is indexed to 100. Is it possible to disable this so that it can go above 100?

**Comment by mikedbjones** [comment]
The purpose of the indexing is that 100 represents the highest result. 100 does not refer to any absolute number of searches. Therefore it would be meaningless to use a number higher than 100.

**Comment by asdsadsaasd12312132** [comment]
But if I wanted to disable the indexing to 100, is it possible?
